baseURL = "//readingrepresentation.com/"
languageCode = "en-us"
title = "Reading Representation"
theme = "osprey-delight"

## Generic theme parameters:
[Params]
  author = ""
  email = ""
  description = "Reading Representation"
  tagline = "The power of story to challenge stereotypes, promote empathy, equality and racial justice."
  logoBig = "/images/title-logo.png"
  # [str] This is the logo that will be shown in the left corner of the nav bar.
  #   Usually, you would like to use something bigger than a favicon - but not too big either.
  #   Make sure that the image does not overlay the nav links. Don't be afraid of experimenting!
  logoSmall = "/images/simple-logo.jpg"
  favicon = "/images/simple-logo.jpg"
  opengraphImage = "/images/simple-logo.jpg"
  googleTagManager = ""
  # [bool] The following will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html'.
  #   This file will only contain a redirect directive if this switch is enabled (recommended, since this is a one-page theme).
  enforceSinglePage = false
  # [bool] Will generate copyright notice in footer for your site.
  copyright = true
  # [bool] Your credit is much appreciated. It will be displayed in a small way in your footer.
  #   Anyways, of course you're free to uncomment the following line to disable the credit.
  # credit = false

## Theme features:
[Params.Feat]
  # [bool] Lazy loading of images with lazysizes (SEO-friendly).
  lazyloading = true
  # [bool] Enable the optional blog module
  useBlog = true

[[menu.main]]
  name = "About"
  url  = "/#about"
  weight = 1
[[menu.main]]
  name = "Books"
  url  = "/#work"
  weight = 2
[[menu.main]]
  name = "Updates"
  url  = "/#blog"
  weight = 3
  
  
[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]


[[deployment.targets]]
# An arbitrary name for this target.
name = "mydeployment"
# The Go Cloud Development Kit URL to deploy to. Examples:
# GCS; see https://gocloud.dev/howto/blob/#gcs
# URL = "gs://<Bucket Name>"

# S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://readingrepresentation.com?region=us-west-2"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

# You can use a "prefix=" query parameter to target a subfolder of the bucket:
# URL = "gs://<Bucket Name>?prefix=a/subfolder/"

# If you are using a CloudFront CDN, deploy will invalidate the cache as needed.
# cloudFrontDistributionID = <ID>

# Optionally, you can include or exclude specific files.
# See https://godoc.org/github.com/gobwas/glob#Glob for the glob pattern syntax.
# If non-empty, the pattern is matched against the local path.
# All paths are matched against in their filepath.ToSlash form.
# If exclude is non-empty, and a local or remote file's path matches it, that file is not synced.
# If include is non-empty, and a local or remote file's path does not match it, that file is not synced.
# As a result, local files that don't pass the include/exclude filters are not uploaded to remote,
# and remote files that don't pass the include/exclude filters are not deleted.
# include = "**.html" # would only include files with ".html" suffix
# exclude = "**.{jpg, png}" # would exclude files with ".jpg" or ".png" suffix


# [[deployment.matchers]] configure behavior for files that match the Pattern.
# Samples:

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
